DiglettsCave_Script:
	jp EnableAutoTextBoxDrawing

DiglettsCave_TextPointers:
	def_text_pointers
	dw_const DiglettsCaveDiglettText, TEXT_DIGLETTSCAVE_DIGLETT

DiglettsCaveDiglettText:
	text_far _DiglettsCaveDiglettText
	text_end
